module.exports = {
    
    // Success
    SUCCESS : { "isSuccess": true, "code": 1000, "message":"성공" }, //조회
    SIGN_UP_SUCCESS : { "isSuccess": true, "code": 1100, "message":"회원가입에 성공하였습니다." },
    EMAIL_CONFIRM_SUCCESS : { "isSuccess": true, "code": 1101, "message":"사용가능한 이메일입니다." },
    NICKNAME_CONFIRM_SUCCESS : { "isSuccess": true, "code": 1102, "message":"사용가능한 닉네임입니다." },
    SIGN_IN_SUCCESS : { "isSuccess": true, "code": 1103, "message":"로그인에 성공하였습니다." },
    SOCIAL_SIGNIN_SUCCESS : { "isSuccess": true, "code": 1104, "message":"소셜 로그인에 성공하였습니다." },
    NEED_SIGN_UP : { "isSuccess": true, "code": 1105, "message":"회원가입이 필요한 계정입니다." },
    FIND_PASSWORD_SUCCESS : { "isSuccess": true, "code": 1106, "message":"해당 핸드폰 번호로 임시 비밀번호를 발송하였습니다." },
    PASSWORD_CORRESPOND_SUCCESS : { "isSuccess": true, "code": 1107, "message":"비밀번호가 일치합니다." },
    PASSWORD_UPDATE_SUCCESS : { "isSuccess": true, "code": 1108, "message":"비밀번호가 변경되었습니다." },
    NICKNAME_UPDATE_SUCCESS : { "isSuccess": true, "code": 1109, "message":"닉네임이 변경되었습니다." },
    USER_INFO_UPDATE_SUCCESS : { "isSuccess": true, "code": 1110, "message":"회원정보가 변경되었습니다." },
    USER_DROP_SUCCESS : { "isSuccess": true, "code": 1111, "message":"회원탈퇴에 성공하였습니다." },
    VERIFICATION_SUCCESS : { "isSuccess": true, "code": 1112, "message":"토큰 검증에 성공하였습니다." },

     // Common
     TOKEN_EMPTY : { "isSuccess": false, "code": 2000, "message":"토큰을 입력해주세요." },
     TOKEN_VERIFICATION_FAILURE : { "isSuccess": false, "code": 3000, "message":"토큰 검증 실패" },
     TOKEN_VERIFICATION_SUCCESS : { "isSuccess": true, "code": 1001, "message":"토큰 검증 성공" }, 
    
     //Requst error
     NAME_EMPTY : { "isSuccess": false, "code": 2047, "message":"유저 이름을 입력해 주세요." },
     NAME_ERROR_TYPE : { "isSuccess": false, "code": 2048, "message":"유저 이름을 형식에 맞게 입력해 주세요." },
     NAME_NOT_EXIST : { "isSuccess": false, "code": 2049, "message":"해당 유저가 존재하지 않습니다." },
     EXAM_ERROR_TYPE : { "isSuccess": false, "code": 2050, "message":"examIdx를 형식에 맞게 입력해 주세요." },
     EXAM_NOT_EXIST : { "isSuccess": false, "code": 2051, "message":"해당 examIdx가 존재하지 않습니다." },
     EXAM_EMPTY : { "isSuccess": false, "code": 2052, "message":"examIdx를 입력해 주세요." },
     EXAMDETAIL_EMPTY : { "isSuccess": false, "code": 2053, "message":"examDetailIdx를 입력해 주세요." },
     EXAMDETAIL_ERROR_TYPE : { "isSuccess": false, "code": 2054, "message":"examDetailIdx를 형식에 맞게 입력해 주세요." },
     EXAMDETAIL_NOT_EXIST : { "isSuccess": false, "code": 2055, "message":"해당 examDetailIdx가 존재하지 않습니다." },
     EMAIL_ERROR_TYPE : { "isSuccess": false, "code": 2056, "message":"이메일을 형식에 맞게 입력해 주세요." },
     EMAIL_NOT_EXIST : { "isSuccess": false, "code": 2057, "message":"해당 이메일이 존재하지 않습니다." },
     EMAIL_EMPTY : { "isSuccess": false, "code": 2058, "message":"이메일을 입력해 주세요." },
     PASSWORD_ERROR_TYPE : { "isSuccess": false, "code": 2059, "message":"비밀번호를 형식에 맞게 입력해 주세요." },
     PASSWORD_EMPTY : { "isSuccess": false, "code": 2060, "message":"비밀번호를 입력해 주세요." },
     PHONENUM_ERROR_TYPE : { "isSuccess": false, "code": 2061, "message":"핸드폰 번호를 형식에 맞게 입력해 주세요." },
     PHONENUM_EMPTY : { "isSuccess": false, "code": 2062, "message":"핸드폰 번호를 입력해 주세요." },
     USERNAME_ERROR_TYPE : { "isSuccess": false, "code": 2063, "message":"유저 이름을 형식에 맞게 입력해 주세요." },
     USERNAME_EMPTY : { "isSuccess": false, "code": 2064, "message":"유저 이름을 입력해 주세요." },
     GENDER_ERROR_TYPE : { "isSuccess": false, "code": 2065, "message":"성별을 형식에 맞게 입력해 주세요." },
     GENDER_EMPTY : { "isSuccess": false, "code": 2066, "message":"성별을 입력해 주세요." },
     DATEOFBIRTH_ERROR_TYPE : { "isSuccess": false, "code": 2067, "message":"생년월일을 형식에 맞게 입력해 주세요." },
     DATEOFBIRTH_EMPTY : { "isSuccess": false, "code": 2068, "message":"생년월일을 입력해 주세요." },
     NICKNAME_ERROR_TYPE : { "isSuccess": false, "code": 2069, "message":"닉네임을 형식에 맞게 입력해 주세요." },
     NICKNAME_EMPTY : { "isSuccess": false, "code": 2070, "message":"닉네임을 입력해 주세요." },
     EMAIL_LENGTH_ERROR : { "isSuccess": false, "code": 2071, "message":"이메일의 길이가 맞지 않습니다. 30자 이내로 입력해주세요." },
     PASSWORD_LENGTH_ERROR : { "isSuccess": false, "code": 2072, "message":"비밀번호의 길이가 맞지 않습니다." },
     DATEOFBIRTH_LENGTH_ERROR : { "isSuccess": false, "code": 2073, "message":"생년월일의 길이가 맞지 않습니다." },
     GENDER_LENGTH_ERROR : { "isSuccess": false, "code": 2074, "message":"성별의 길이가 맞지 않습니다." },
     NICKNAME_LENGTH_ERROR : { "isSuccess": false, "code": 2075, "message":"닉네임의 길이가 맞지 않습니다. 8자 이내로 입력해주세요." },
     EMAIL_EXIST : { "isSuccess": false, "code": 2076, "message":"해당 이메일이 이미 존재합니다." },
     PHONENUM_NOT_EXIST : { "isSuccess": false, "code": 2077, "message":"해당 핸드폰 번호가 존재하지 않습니다." },
     PHONENUM_EXIST : { "isSuccess": false, "code": 2078, "message":"해당 핸드폰 번호가 이미 존재합니다." },
     EMAIL_SEND_ERROR : { "isSuccess": false, "code": 20879, "message":"메일 발송을 실패하였습니다." },
     USER_NOT_EXIST : { "isSuccess": false, "code": 2080, "message":"존재하지 않는 계정입니다." },
     USER_QUIT : { "isSuccess": false, "code": 2081, "message":"탈퇴한 계정입니다." },
     USER_NOT_MATCH : { "isSuccess": false, "code": 2082, "message":"입력하신 유저 인덱스와 토큰값이 일치하지 않습니다." },
     USER_ERROR_TYPE : { "isSuccess": false, "code": 2083, "message":"유저 인덱스를 형식에 맞게 입력해 주세요." },
     USER_EMPTY : { "isSuccess": false, "code": 2084, "message":"유저 인덱스를 입력해 주세요." },
     PASSWORD_NOT_MATCH : { "isSuccess": false, "code": 2085, "message":"비밀번호가 틀렸습니다." },
     NICKNAME_EXIST : { "isSuccess": false, "code": 2086, "message":"해당 닉네임이 이미 존재합니다." },
     REVIEWNOTE_EXIST : { "isSuccess": false, "code": 2087, "message":"해당 오답노트가 이미 존재합니다." },
     SOCIAL_SIGNIN_FAIL : { "isSuccess": false, "code": 2088, "message":"소셜 로그인에 실패하였습니다." },
     ACCESS_TOKEN_FAIL : { "isSuccess": false, "code": 2089, "message":"유효하지 않은 토큰입니다." },
     EXAMSORT_EMPTY : { "isSuccess": false, "code": 2090, "message":"examSort를 입력해주세요." },
     EXAMSORT_ERROR_TYPE : { "isSuccess": false, "code": 2091, "message":"examSort를 형식에 맞게 입력해주세요." },
     ANSWERLIST_LENGTH_ERROR : { "isSuccess": false, "code": 2092, "message":"answerList를 길이에 맞게 입력해주세요." },
     ANSWERLIST_EMPTY : { "isSuccess": false, "code": 2093, "message":"answerList를 입력해주세요." },
     ANSWERLIST_ERROR_TYPE : { "isSuccess": false, "code": 2094, "message":"answerList를 형식에 맞게 입력해주세요." },
     ANSWERLIST_NOT_EXIST : { "isSuccess": false, "code": 2095, "message":"answerList가 존재하지 않습니다." },
     PROBLEM_EMPTY : { "isSuccess": false, "code": 2096, "message":"문제 인덱스를 입력해주세요." },
     PROBLEM_ERROR_TYPE : { "isSuccess": false, "code": 2097, "message":"문제 인덱스를 형식에 맞게 입력해주세요." },
     PROBLEM_NOT_EXIST : { "isSuccess": false, "code": 2098, "message":"문제 인덱스가 존재하지 않습니다." },
     CORRECT_EMPTY : { "isSuccess": false, "code": 2099, "message":"correct를 입력해주세요." },
     CORRECT_ERROR_TYPE : { "isSuccess": false, "code": 2100, "message":"correct를 형식에 맞게 입력해주세요." },
     PROBLEMIDX_EMPTY : { "isSuccess": false, "code": 2101, "message":"problemIdx를 입력해주세요." },
     PROBLEMIDX_ERROR_TYPE : { "isSuccess": false, "code": 2102, "message":"problemIdx를 형식에 맞게 입력해주세요." },
     ARRAY_LENGTH_ERROR : { "isSuccess": false, "code": 2103, "message":"각각의 배열을 길이에 맞게 입력해주세요." },
     AUTH_NUMBER_EMPTY : { "isSuccess": false, "code": 2104, "message":"인증번호를 입력해주세요." },
     AUTH_NUMBER_ERROR_TYPE : { "isSuccess": false, "code": 2105, "message":"인증번호를 형식에 맞게 입력해주세요." },
     REVIEWNOTE_NOT_EXIST : { "isSuccess": false, "code": 2106, "message":"해당 오답노트가 존재하지 않습니다." },
     SCORE_EMPTY : { "isSuccess": false, "code": 2107, "message":" 점수를 입력해 주세요. " },
     SCORE_ERROR_TYPE : { "isSuccess": false, "code": 2108, "message":" 점수를 형식에 맞게 입력해 주세요. " },
     BOARDTITLE_EMPTY : { "isSuccess": false, "code": 2109, "message":" 제목을 입력해 주세요. " },
     BOARDCONTENT_EMPTY : { "isSuccess": false, "code": 2110, "message":" 내욜을 입력해 주세요. " },
     BOARDIDX_EMPTY : { "isSuccess": false, "code": 2111, "message":" boardIdx를 입력해 주세요. " },
     BOARDIDX_ERROR_TYPE : { "isSuccess": false, "code": 2112, "message":" boardIdx를 형식에 맞게 입력해 주세요. " },
     BOARDIDX_NOT_EXIST : { "isSuccess": false, "code": 2113, "message":" 삭제된 게시글입니다. " },
     BOARDIDX_NOT_MATCH : { "isSuccess": false, "code": 2114, "message":" 문제 오류 게시글이 아닙니다. " },
     EXAMRECORD_EMPTY : { "isSuccess": false, "code": 2115, "message":" examRecordIdx를 입력해 주세요. " },
     EXAMRECORD_ERROR_TYPE : { "isSuccess": false, "code": 2116, "message":" examRecordIdx를 형식에 맞게 입력해 주세요. " },
     EXAMRECORD_NOT_EXIST : { "isSuccess": false, "code": 2117, "message":" examRecordIdx가 존재하지 않습니다. " },
     PROBLEMNUM_EMPTY : { "isSuccess": false, "code": 2118, "message":" 문제 번호를 입력해 주세요. " },
     PROBLEM_EMPTY : { "isSuccess": false, "code": 2119, "message":" 문제를 입력해 주세요. " },
     ANSWER_EMPTY : { "isSuccess": false, "code": 2120, "message":" 답을 입력해 주세요. " },
     SOLUTION_EMPTY : { "isSuccess": false, "code": 2121, "message":" 해설을 입력해 주세요. " },
     EXAMSUBJECT_EMPTY : { "isSuccess": false, "code": 2122, "message":" 과목 인덱스를 입력해 주세요. " },
     ISKATEX_EMPTY : { "isSuccess": false, "code": 2123, "message":" 카텍스 유무를 입력해 주세요. " },
     QUESTIONNUM_EMPTY : { "isSuccess": false, "code": 2124, "message":" 문항 번호를 입력해 주세요. " },
     QUESTION_EMPTY : { "isSuccess": false, "code": 2125, "message":" 문항 내용을 입력해 주세요. " },
     PROBLEMIDX_EXIST : { "isSuccess": false, "code": 2126, "message":" 이미 존재하는 문제인덱스입니다. " },
     EXAMNAME_EXIST : { "isSuccess": false, "code": 2127, "message":" 이미 존재하는 시험 이름입니다. " },
     USER_INVINCIBILITY : { "isSuccess": false, "code": 2128, "message":" 변경할 수 없는 회원입니다. " },
     USER_PROCESSED : { "isSuccess": false, "code": 2129, "message":" 이미 처리된 회원입니다. " },
     SIGNIN_PASSWORD_WRONG : { "isSuccess": false, "code": 2130, "message":" 잘못된 비밀번호입니다. . " },
     DROP_USER : { "isSuccess": false, "code": 2131, "message":" 탈퇴한 회원입니다. " },
     EXAMDETAIL_EXIST : { "isSuccess": false, "code": 2132, "message":" 이미 존재하는 시험 회차입니다. " },
     ESSENTIAL_EMPTY : { "isSuccess": false, "code": 2133, "message":" 필수 값을 입력해 주세요. " },
     EXAMSUBJECT_NOT_EXIST : { "isSuccess": false, "code": 2134, "message":" 존재하지 않는 과목입니다. " },
     EXAMSUBJECTNAME_EMPTY : { "isSuccess": false, "code": 2135, "message":" 시험 과목이름을 입력해 주세요. " },
     EXAMSUBJECTNUM_EMPTY : { "isSuccess": false, "code": 2136, "message":" 시험 과목번호를 입력해 주세요. " },
     IMPOSSIBLE_VALUE_ERROR : { "isSuccess": false, "code": 2137, "message":" 불가능한 값을 입력하였습니다. 다시 확인하여 주세요. " },
     PROBLEM_SUBJECT_EXIST : { "isSuccess": false, "code": 2138, "message":" 해당 회차 과목의 문제번호가 이미 존재합니다. " },
     DATA_ERROR_TYPE : { "isSuccess": false, "code": 2139, "message":" 해당 데이터타입의 맞게 입력해주세요. " },
     NICKNAME_NOT_EXIST : { "isSuccess": false, "code": 2140, "message":" 존재하지 않는 닉네임입니다. " },
     EXAMSORT_EXIST : { "isSuccess": false, "code": 2141, "message":" 이미 존재하는 시험 종류입니다. " },
     EXAMSORTREF_EMPTY : { "isSuccess": false, "code": 2142, "message":" 시험 구분을 입력해 주세요. " },
     EXAMSORT_NOT_EXIST : { "isSuccess": false, "code": 2143, "message":" 존재하지 않는 시험 종류입니다. " },
     MODEXAMSORT_EMPTY : { "isSuccess": false, "code": 2144, "message":" 변경할 시험 종류를 입력해 주세요. " },
     MODEXAMSORTREF_EMPTY : { "isSuccess": false, "code": 2145, "message":" 변경할 시험 구분을 입력해 주세요. " },
     EXAMSORTREF_NOT_EXIST : { "isSuccess": false, "code": 2146, "message":" 존재하지 않는 시험 구분입니다. " },
     PROBLEM_SUBJECT_EXIST : { "isSuccess": false, "code": 2147, "message":" 연결되어 있는 문제가 존재합니다.  " },
     EXAM_EXIST_EXAMDETAIL : { "isSuccess": false, "code": 2148, "message":" 해당 시험에 시험회차를 먼저 삭제해주세요.  " },

     //Connection, Transaction 등의 서버 오류
    DB_ERROR : { "isSuccess": false, "code": 4000, "message": "데이터 베이스 에러"},
    SERVER_ERROR : { "isSuccess": false, "code": 4001, "message": "서버 에러"},
 
}